# Generated by Django 5.2.11 on 2026-02-13 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('staff', '원내 입력'), ('patient', '환자 입력')], default='patient', max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='clinic.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='clinic.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'code', '-recorded_at'], name='clinic_obse_patient_4e5333_idx')],
            },
        ),
    ]
